### ISSUE TITLE
Without warning, advertising it would do so, or asking this extension changed my new tab page. 

### ISSUE THREAD

**Issue by mikhoul** [Vadagon/volume-manager#1]
Without warning, advertising it would do so, or asking this extension changed my new tab page. 

Shady.  Stay away.

Source: https://chrome.google.com/webstore/detail/volume-manager/kakeffogmhndegdafnbobknemagiikak

**Comment by Jordy3D** [comment]
Seriously shady
At the very least, you can load an old version unpacked to get the old functionality without the crappy actions implemented in this recent update

**Comment by Vadagon** [comment]
The extension on the web store you are talking about isn't mine anymore.

**Comment by Jordy3D** [comment]
Might be best to mention that on your Git somewhere or something, the current owner if indeed it's not you is being shady and not telling users about these things.

**Comment by mikhoul** [comment]
[**@Vadagon**](https://github.com/Vadagon) commented on [12 févr. 2019 à 17:21 UTC−5](https://github.com/Vadagon/volume-manager/issues/1#issuecomment-462960561 "2019-02-12T22:21:22Z - Replied by Github Reply Comments"):
> The extension on the web store you are talking about isn't mine anymore.

![image](https://user-images.githubusercontent.com/5678673/52684062-dde1f280-2f12-11e9-8c75-0f73bb9e0cd6.png)


![image](https://user-images.githubusercontent.com/5678673/52684056-d7537b00-2f12-11e9-8670-9e55829f2853.png)

![image](https://user-images.githubusercontent.com/5678673/52684116-11bd1800-2f13-11e9-9281-6dc4944776c3.png)

**Comment by Vadagon** [comment]
My bad. I'm sorry for any troubles.
